### ISSUE TITLE
Hermann producer should support partition keys

### ISSUE THREAD

**Issue by trane** [lookout/hermann#28]
There are all sorts of partition keys that we could use, providing a way to specify a key per message is already supported in scala kafka.

I see this as a Partitioner class that is specified on producer creation, and a key on each message that is run through the Partitioner class. 

A *very* rough psuedo-code example:

```
class GuidPartitioner
   # somehow get the number of partitions for a topic
   def initialize(topic_metadata)
      @partition_count = topic_metadata.get partitions
   end
   # guids are uniformly distributed, so a simple mod on partition_count should get a good distribution
   # guid [UUIDTools::UUID] the guid object
   def select_partition(guid)
       guid.to_i % @partition_count
   end
end
```

The default could be key-less, like it is now

**Comment by rtyler** [comment]
See #121, can't find the JRuby pull request right now. Anyways, this was addressed and released a while ago
